using ClosedXML.Excel;
using PPS.LicenseManager.API.Services.Interfaces;

namespace PPS.LicenseManager.API.Services.ReportCenter;

public class ReportExcelExportService : IReportExcelExportService
{
    private static readonly XLColor HeaderFillColor = XLColor.FromHtml("#DDEBF7");
    private static readonly XLColor TitleFillColor = XLColor.FromHtml("#1E2761");

    public byte[] BuildWorkbook<TRow>(
        ExcelWorkbookMeta meta,
        IReadOnlyList<TRow> rows,
        IReadOnlyList<ExcelColumn<TRow>> columns,
        IReadOnlyList<ExcelBreakdownSheet>? breakdownSheets = null)
    {
        using var workbook = new XLWorkbook();

        BuildSummarySheet(workbook, meta);
        BuildDetailSheet(workbook, rows, columns);

        if (breakdownSheets != null)
        {
            foreach (var breakdown in breakdownSheets)
            {
                BuildBreakdownSheet(workbook, breakdown);
            }
        }

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return stream.ToArray();
    }

    private static void BuildSummarySheet(XLWorkbook workbook, ExcelWorkbookMeta meta)
    {
        var sheet = workbook.Worksheets.Add("Summary");

        sheet.Cell(1, 1).Value = meta.ReportTitle;
        sheet.Cell(1, 1).Style.Font.Bold = true;
        sheet.Cell(1, 1).Style.Font.FontSize = 16;
        sheet.Cell(1, 1).Style.Font.FontColor = XLColor.White;
        sheet.Cell(1, 1).Style.Fill.BackgroundColor = TitleFillColor;
        sheet.Range(1, 1, 1, 4).Merge();
        sheet.Row(1).Height = 24;

        sheet.Cell(3, 1).Value = "Generated By";
        sheet.Cell(3, 1).Style.Font.Bold = true;
        sheet.Cell(3, 2).Value = meta.GeneratedByUserName;

        sheet.Cell(4, 1).Value = "Generated On";
        sheet.Cell(4, 1).Style.Font.Bold = true;
        sheet.Cell(4, 2).Value = meta.GeneratedAtUtc;
        sheet.Cell(4, 2).Style.DateFormat.Format = "yyyy-mm-dd hh:mm";

        sheet.Cell(5, 1).Value = "Record Count";
        sheet.Cell(5, 1).Style.Font.Bold = true;
        sheet.Cell(5, 2).Value = meta.RecordCount;

        sheet.Cell(7, 1).Value = "Applied Filters";
        sheet.Cell(7, 1).Style.Font.Bold = true;
        sheet.Cell(7, 1).Style.Font.FontSize = 12;

        if (meta.AppliedFilters.Count == 0)
        {
            sheet.Cell(8, 1).Value = "None";
        }
        else
        {
            var row = 8;
            foreach (var filter in meta.AppliedFilters)
            {
                sheet.Cell(row, 1).Value = filter.Label;
                sheet.Cell(row, 2).Value = filter.Value;
                row++;
            }
        }

        sheet.Column(1).Width = 22;
        sheet.Column(2).Width = 40;
    }

    private static void BuildDetailSheet<TRow>(
        XLWorkbook workbook,
        IReadOnlyList<TRow> rows,
        IReadOnlyList<ExcelColumn<TRow>> columns)
    {
        var sheet = workbook.Worksheets.Add("Detail");

        for (var c = 0; c < columns.Count; c++)
        {
            var headerCell = sheet.Cell(1, c + 1);
            headerCell.Value = columns[c].Header;
            headerCell.Style.Font.Bold = true;
            headerCell.Style.Fill.BackgroundColor = HeaderFillColor;

            var width = columns[c].Width
                ?? Math.Clamp(columns[c].Header.Length + 6, 10, 40);
            sheet.Column(c + 1).Width = width;
        }

        for (var r = 0; r < rows.Count; r++)
        {
            var excelRow = r + 2;
            for (var c = 0; c < columns.Count; c++)
            {
                var column = columns[c];
                var value = column.ValueSelector(rows[r]);
                var cell = sheet.Cell(excelRow, c + 1);

                SetCellValue(cell, value);
                ApplyNumberFormat(cell, column.Format);
            }
        }

        sheet.SheetView.FreezeRows(1);
        sheet.RangeUsed()?.SetAutoFilter();
    }

    private static void BuildBreakdownSheet(XLWorkbook workbook, ExcelBreakdownSheet breakdown)
    {
        var sheetName = breakdown.SheetName.Length > 31
            ? breakdown.SheetName[..31]
            : breakdown.SheetName;

        var sheet = workbook.Worksheets.Add(sheetName);

        for (var c = 0; c < breakdown.Headers.Count; c++)
        {
            var headerCell = sheet.Cell(1, c + 1);
            headerCell.Value = breakdown.Headers[c];
            headerCell.Style.Font.Bold = true;
            headerCell.Style.Fill.BackgroundColor = HeaderFillColor;
            sheet.Column(c + 1).Width = Math.Clamp(breakdown.Headers[c].Length + 6, 10, 40);
        }

        for (var r = 0; r < breakdown.Rows.Count; r++)
        {
            var excelRow = r + 2;
            var dataRow = breakdown.Rows[r];
            for (var c = 0; c < dataRow.Length; c++)
            {
                SetCellValue(sheet.Cell(excelRow, c + 1), dataRow[c]);
            }
        }

        sheet.SheetView.FreezeRows(1);
        sheet.RangeUsed()?.SetAutoFilter();
    }

    private static void SetCellValue(IXLCell cell, object? value)
    {
        switch (value)
        {
            case null:
                break;
            case string s:
                cell.Value = s;
                break;
            case DateTime dt:
                cell.Value = dt;
                cell.Style.DateFormat.Format = "yyyy-mm-dd";
                break;
            case DateOnly d:
                cell.Value = d.ToDateTime(TimeOnly.MinValue);
                cell.Style.DateFormat.Format = "yyyy-mm-dd";
                break;
            case decimal dec:
                cell.Value = dec;
                break;
            case double dbl:
                cell.Value = dbl;
                break;
            case float f:
                cell.Value = (double)f;
                break;
            case int i:
                cell.Value = i;
                break;
            case long l:
                cell.Value = l;
                break;
            case bool b:
                cell.Value = b ? "Yes" : "No";
                break;
            default:
                cell.Value = value.ToString();
                break;
        }
    }

    private static void ApplyNumberFormat(IXLCell cell, ExcelNumberFormat format)
    {
        switch (format)
        {
            case ExcelNumberFormat.Currency:
                cell.Style.NumberFormat.Format = "#,##0.00";
                break;
            case ExcelNumberFormat.Date:
                cell.Style.DateFormat.Format = "yyyy-mm-dd";
                break;
            case ExcelNumberFormat.Percent:
                cell.Style.NumberFormat.Format = "0.0%";
                break;
            case ExcelNumberFormat.Number:
                cell.Style.NumberFormat.Format = "#,##0";
                break;
        }
    }
}
